- name: Make sure no old maldet folders are lurking here
  shell: rm -rf /tmp/maldetect* removes=/tmp/maldetect*

- name: Download maldet
  get_url: url={{ maldet_download }} dest=/tmp/{{ maldet_download_file }}

- name: create directory
  file: path=/tmp/maldetect-install state=directory owner=root group=root mode=0755

- name: Untar maldet
  unarchive: src=/tmp/{{ maldet_download_file }}  dest=/tmp/maldetect-install copy=no
  #shell: tar xvzf {{ maldet_download_file }} -C /tmp/maldetect-install chdir=/tmp

- name: Run the maldet installer
  shell: ./install.sh chdir=/tmp/maldetect-install

- name: Copy over conf.maldet
  template: src=conf.maldet.j2 dest=/usr/local/maldetect/conf.maldet owner=root group=root mode=0644
  tags: conf.maldet

- name: copy cron daily
  action: copy src=../files/maldet_scan dest=/etc/cron.daily/ owner=root group=root mode="755"

- name: copy cron hourly
  action: copy src=../files/maldet_report dest=/etc/cron.hourly/ owner=root group=root mode="755"
